/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world


import io.javalin.Javalin

fun main() {
    val app = Javalin.create().start(7000)
    app.get("/") { ctx -> ctx.result("Hello World") }
}